// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/bookstore/models"
)

// BookHistoryOKCode is the HTTP code returned for type BookHistoryOK
const BookHistoryOKCode int = 200

/*BookHistoryOK A mapping of book ISBNs to book history.

swagger:response bookHistoryOK
*/
type BookHistoryOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.History `json:"body,omitempty"`
}

// NewBookHistoryOK creates BookHistoryOK with default headers values
func NewBookHistoryOK() *BookHistoryOK {

	return &BookHistoryOK{}
}

// WithPayload adds the payload to the book history o k response
func (o *BookHistoryOK) WithPayload(payload map[string]models.History) *BookHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book history o k response
func (o *BookHistoryOK) SetPayload(payload map[string]models.History) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.History, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*BookHistoryDefault Unexpected error.

swagger:response bookHistoryDefault
*/
type BookHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookHistoryDefault creates BookHistoryDefault with default headers values
func NewBookHistoryDefault(code int) *BookHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &BookHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book history default response
func (o *BookHistoryDefault) WithStatusCode(code int) *BookHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book history default response
func (o *BookHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book history default response
func (o *BookHistoryDefault) WithPayload(payload *models.Error) *BookHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book history default response
func (o *BookHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
