// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// BookCheckoutHandlerFunc turns a function with the right signature into a book checkout handler
type BookCheckoutHandlerFunc func(BookCheckoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookCheckoutHandlerFunc) Handle(params BookCheckoutParams) middleware.Responder {
	return fn(params)
}

// BookCheckoutHandler interface for that can handle valid book checkout params
type BookCheckoutHandler interface {
	Handle(BookCheckoutParams) middleware.Responder
}

// NewBookCheckout creates a new http.Handler for the book checkout operation
func NewBookCheckout(ctx *middleware.Context, handler BookCheckoutHandler) *BookCheckout {
	return &BookCheckout{Context: ctx, Handler: handler}
}

/* BookCheckout swagger:route POST /api/checkout api bookCheckout

Check out the given books.

*/
type BookCheckout struct {
	Context *middleware.Context
	Handler BookCheckoutHandler
}

func (o *BookCheckout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookCheckoutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
