// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/bookstore/models"
)

// BookReadOKCode is the HTTP code returned for type BookReadOK
const BookReadOKCode int = 200

/*BookReadOK A map of ISBNs to book data for the requested books.

swagger:response bookReadOK
*/
type BookReadOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.Book `json:"body,omitempty"`
}

// NewBookReadOK creates BookReadOK with default headers values
func NewBookReadOK() *BookReadOK {

	return &BookReadOK{}
}

// WithPayload adds the payload to the book read o k response
func (o *BookReadOK) WithPayload(payload map[string]models.Book) *BookReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book read o k response
func (o *BookReadOK) SetPayload(payload map[string]models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.Book, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*BookReadDefault Unexpected error.

swagger:response bookReadDefault
*/
type BookReadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookReadDefault creates BookReadDefault with default headers values
func NewBookReadDefault(code int) *BookReadDefault {
	if code <= 0 {
		code = 500
	}

	return &BookReadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book read default response
func (o *BookReadDefault) WithStatusCode(code int) *BookReadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book read default response
func (o *BookReadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book read default response
func (o *BookReadDefault) WithPayload(payload *models.Error) *BookReadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book read default response
func (o *BookReadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookReadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
