// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/bookstore/models"
)

// BookCheckoutOKCode is the HTTP code returned for type BookCheckoutOK
const BookCheckoutOKCode int = 200

/*BookCheckoutOK The books have been checked out.

swagger:response bookCheckoutOK
*/
type BookCheckoutOK struct {
}

// NewBookCheckoutOK creates BookCheckoutOK with default headers values
func NewBookCheckoutOK() *BookCheckoutOK {

	return &BookCheckoutOK{}
}

// WriteResponse to the client
func (o *BookCheckoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*BookCheckoutDefault Unexpected error.

swagger:response bookCheckoutDefault
*/
type BookCheckoutDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookCheckoutDefault creates BookCheckoutDefault with default headers values
func NewBookCheckoutDefault(code int) *BookCheckoutDefault {
	if code <= 0 {
		code = 500
	}

	return &BookCheckoutDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book checkout default response
func (o *BookCheckoutDefault) WithStatusCode(code int) *BookCheckoutDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book checkout default response
func (o *BookCheckoutDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book checkout default response
func (o *BookCheckoutDefault) WithPayload(payload *models.Error) *BookCheckoutDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book checkout default response
func (o *BookCheckoutDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookCheckoutDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
