// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/bookstore/models"
)

// BookStatusOKCode is the HTTP code returned for type BookStatusOK
const BookStatusOKCode int = 200

/*BookStatusOK A mapping of book ISBNs to book status.

swagger:response bookStatusOK
*/
type BookStatusOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.Status `json:"body,omitempty"`
}

// NewBookStatusOK creates BookStatusOK with default headers values
func NewBookStatusOK() *BookStatusOK {

	return &BookStatusOK{}
}

// WithPayload adds the payload to the book status o k response
func (o *BookStatusOK) WithPayload(payload map[string]models.Status) *BookStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book status o k response
func (o *BookStatusOK) SetPayload(payload map[string]models.Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.Status, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*BookStatusDefault Unexpected error.

swagger:response bookStatusDefault
*/
type BookStatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookStatusDefault creates BookStatusDefault with default headers values
func NewBookStatusDefault(code int) *BookStatusDefault {
	if code <= 0 {
		code = 500
	}

	return &BookStatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book status default response
func (o *BookStatusDefault) WithStatusCode(code int) *BookStatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book status default response
func (o *BookStatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book status default response
func (o *BookStatusDefault) WithPayload(payload *models.Error) *BookStatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book status default response
func (o *BookStatusDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookStatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
