// Code generated by go-swagger; DO NOT EDIT.

// Package restapi bookstore
//
//  A bookstore coding challenge
//  Schemes:
//    http
//    https
//  Host: bookstore.micahparks.com
//  BasePath: /
//  Version: 0.0.1
//  License: MIT https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
