// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// StatusType status type
//
// swagger:model StatusType
type StatusType string

const (

	// StatusTypeCheckin captures enum value "checkin"
	StatusTypeCheckin StatusType = "checkin"

	// StatusTypeCheckout captures enum value "checkout"
	StatusTypeCheckout StatusType = "checkout"
)

// for schema
var statusTypeEnum []interface{}

func init() {
	var res []StatusType
	if err := json.Unmarshal([]byte(`["checkin","checkout"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		statusTypeEnum = append(statusTypeEnum, v)
	}
}

func (m StatusType) validateStatusTypeEnum(path, location string, value StatusType) error {
	if err := validate.EnumCase(path, location, value, statusTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this status type
func (m StatusType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateStatusTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this status type based on context it is used
func (m StatusType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
